### ISSUE TITLE
failed calling webhook "webhook.cert-manager.io":

### ISSUE THREAD

**Issue by DreamerCather** [Eros11on/Dockerfile-library#1]
WARN[0020] Encountered error applying application cert-manager:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout083162922": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:202"
WARN[0020] Will retry in 9 seconds.                      filename="kustomize/kustomize.go:203"

你好，我参考了https://blog.csdn.net/qq_46595591/article/details/107765833进行安装kubeflow，发现循环输出上述错误，请问你安装的时候有遇到过吗

**Comment by Eros11on** [comment]
你好 这个情况应该是kustomize中的某些文件丢失，建议直接下载kustomize到服务器，或者通过源码查看filename =“ kustomize / kustomize.go：203”第203行所提示的代码，将缺失文件补充进来

**Comment by DreamerCather** [comment]
大佬，我补充下全部错误如下：
ERRO[0632] Permanently failed applying application cert-manager; error:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout585762364": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request  filename="kustomize/kustomize.go:206"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout585762364": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                      		export CONFIG=./kfctl_gcp_iap.yaml
                      	or a URL:
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                      		export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                      	kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout585762364": Internal error occurred: failed calling webhook "webhook.cert-manager.io": the server is currently unable to handle the request

我在kubeflow issues也查询到了很多类似的，发现有很多类似的，但是尝试了他们的解决方案貌似没啥用，执行cert-manager查看：
kubectl get apiservices | grep webhook
v1beta1.webhook.cert-manager.io        cert-manager/cert-manager-webhook   False (FailedDiscoveryCheck)   33m
想问下你们搭建的集群这个配置正确吗？
kubectl get apiservice v1beta1.webhook.cert-manager.io -o yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-tls
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiregistration.k8s.io/v1beta1","kind":"APIService","metadata":{"annotations":{"cert-manager.io/inject-ca-from-secret":"cert-manager/cert-manager-webhook-tls"},"labels":{"app":"webhook","app.kubernetes.io/component":"cert-manager","app.kubernetes.io/instance":"cert-manager-v1.0.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"cert-manager","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"v1.0.0","kustomize.component":"cert-manager"},"name":"v1beta1.webhook.cert-manager.io"},"spec":{"group":"webhook.cert-manager.io","groupPriorityMinimum":1000,"service":{"name":"cert-manager-webhook","namespace":"cert-manager"},"version":"v1beta1","versionPriority":15}}
  creationTimestamp: "2020-08-10T08:49:18Z"
  labels:
    app: webhook
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/instance: cert-manager-v1.0.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v1.0.0
    kustomize.component: cert-manager
  name: v1beta1.webhook.cert-manager.io
  resourceVersion: "140250"
  selfLink: /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.webhook.cert-manager.io
  uid: 02e18899-cbc2-4b13-abf1-34505be1908d
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMakNDQWhhZ0F3SUJBZ0lSQUlIQ2p2bTY5K2ZqNHdnYkY4Z3ViaWd3RFFZSktvWklodmNOQVFFTEJRQXcKUURFY01Cb0dBMVVFQ2hNVFkyVnlkQzF0WVc1aFoyVnlMbk41YzNSbGJURWdNQjRHQTFVRUF4TVhZMlZ5ZEMxdApZVzVoWjJWeUxuZGxZbWh2YjJzdVkyRXdIaGNOTWpBd09ERXdNRGcxTURJNVdoY05NalV3T0RBNU1EZzFNREk1CldqQkFNUnd3R2dZRFZRUUtFeE5qWlhKMExXMWhibUZuWlhJdWMzbHpkR1Z0TVNBd0hnWURWUVFERXhkalpYSjAKTFcxaGJtRm5aWEl1ZDJWaWFHOXZheTVqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQU43ZEdiZ1h3VmxjS1ZCaFVNMEk3OTFTMElLSVBVdHNrZXdlN0s0QkpWTzZYYkVxVVBSQXNTVnpLRnV0CnZ1Uk5OUTZuUlZ1dlVCR29CeHFMOGt3eXF4QURpb0lrTytmQmRNVCtPaFJsSENSbmtYbDZhbnUvam80bmxIMlQKMHFWdy9zbHg5b2JYa3llYjhCS1BtY1Y4a2gzRGZEL3V6ZnJFcDcySkYwelpIVlQxKy9qOWQ3SXdVSHZlV2Y5YQpxSnVwblVieEs3blB6Y3VpZGJtYlV6YW43SjM2bnhXKzNvcmhGV3k0eUpaM2laeEFWUHVrblRGQTFZZnF2WDdHCi9jb1ZKcjVkK01rTkI1WmNlbzJERU1kRjhWTEloTUlUcFZ1UDA2dmNmYjNWM3VibFRZOFVOWlZRL2dtd3k5TlIKQzk2OWVpVkl4Rk5TbnlGZVhKS2VhS2tHY284Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4RwpBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHOW1wZWp0eEJlbHB6SzRaRHRDCkZQVUtRSHozRUJxWlpEcmFiZzJlUFVpdzJ2aVE4VTVBN3JrR0FEV0k1NlMxbzl5MklGbTVYTlF0amluWWpnV0wKR3pCSWkyMVlxa3YxcUVZRVkvVWhzYmR1TTg5c2JYSXZ2ditGMEtGcXFlOXRUM1NFcWZySVlra1Z4V0ZaQU9aTwp4dVhzT2RMY3pqYUVjU0M3UEczaEIzcWdGbjdsN0RJTnNFeFdGRVRwdW5sUGxKZDVSYm5EVDlwUjlUUExIbTUxCjFBU0RHOWo5ZVlDWS96TGNNcHR1RngrcjV0ME5ZaE9jSmxEYXAvamZlVFdWVUdvdk51K2ttd2ZsUWNZNHdDQXUKSldiamtWdTBoQ0JFVmJEMGZEMlhhSXZMYmlMWjd0cVhhNXdaVUdTWXo1ZXh6MjRXU0t4WHN6eDl2ejNmTE5RLwpJb1E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  group: webhook.cert-manager.io
  groupPriorityMinimum: 1000
  service:
    name: cert-manager-webhook
    namespace: cert-manager
    port: 443
  version: v1beta1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2020-08-10T08:49:18Z"
    message: 'failing or missing response from https://11.1.105.125:443/apis/webhook.cert-manager.io/v1beta1:
      Get "https://11.1.105.125:443/apis/webhook.cert-manager.io/v1beta1": net/http:
      request canceled while waiting for connection (Client.Timeout exceeded while
      awaiting headers)'
    reason: FailedDiscoveryCheck
    status: "False"
    type: Available

**Comment by Eros11on** [comment]
这个情况应该就是网络不稳定 下不了国外的文件 可以试试查看kfctl文件下有没有webhook.cert-manager.io文件，如果有的话可以将它cp到/tmp/kout585762364下   然后重新apply  最好使用1.0.2版本的

**Comment by Eros11on** [comment]
kfctl release page
https://github.com/kubeflow/kubeflow/releases/ 

下载最新（用迅雷下载快一些）
 
下载v1.0.2源码包(任选其一,将文件下载到/root/v1.0.2.tar.gz)
    wget https://github.com/kubeflow/manifests/archive/v1.0.2.tar.gz
    wget https://github.com/kubeflow/kfctl/archive/v1.0.2.tar.gz

下载 yaml 文件
    wget https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml

修改 kfctl_k8s_istio.v1.0.2.yaml 内容 ()
将 https://github.com/kubeflow/manifests/archive/v1.0.2.tar.gz 改为 file:///root/kubeflow/v1.0.2.tar.gz


开始部署
1
 

2
阿里云 构建拉取所需要的镜像
 
3.创建pv
 
4.修改各个deploy statefulset 的镜像下载策略 ，因为下载策略是Always ，需要修改为（imagePullPolicy后面值改为 IfNotPresent）

例子
#kubectl edit deploy deploy名字 -n kubeflow

**Comment by Eros11on** [comment]
或许你可以留一个邮箱 我可以把自己整理的一个部署文档发给你 参考一下

**Comment by DreamerCather** [comment]
2945360190@qq.com，3q3q，我执行kubect get apiservices | grep webhook显示如下：
v1beta1.webhook.cert-manager.io        cert-manager/cert-manager-webhook   False (FailedDiscoveryCheck)   47h
然后导致kubeflow命名空间下的pods不能安装，只有如下：
kubectl get pods -n kubeflow
NAME                                    READY   STATUS    RESTARTS   AGE
application-controller-stateful-set-0   1/1     Running   2          47h
但是kubectl get pods -n istio-system是正确的
kubectl get pods -n istio-system
NAME                                        READY   STATUS      RESTARTS   AGE
cluster-local-gateway-748f94c9ff-zg9s2      1/1     Running     0          47h
grafana-67c69bb567-vv78b                    1/1     Running     0          47h
istio-citadel-67697b6697-rldrn              1/1     Running     0          47h
istio-cleanup-secrets-1.1.6-6zskv           0/1     Completed   0          47h
istio-egressgateway-7dbbb87698-42796        1/1     Running     3          47h
istio-galley-7bffd57ff4-q2q98               1/1     Running     0          47h
istio-grafana-post-install-1.1.6-qn295      0/1     Completed   0          47h
istio-ingressgateway-565b894b5f-jbr6k       1/1     Running     4          47h
istio-pilot-6dd5b8f74c-xmhng                2/2     Running     0          47h
istio-policy-7f8bb87857-c4pjl               2/2     Running     1          47h
istio-security-post-install-1.1.6-tlbkh     0/1     Completed   0          47h
istio-sidecar-injector-fd5875568-bhl5f      1/1     Running     0          47h
istio-telemetry-8759dc6b7-dt8hn             2/2     Running     0          47h
istio-tracing-5d8f57c8ff-f6ttq              1/1     Running     0          47h
kfserving-ingressgateway-598c9fd4ff-p2gbf   1/1     Running     1          47h
kiali-d4d886dd7-78hv5                       1/1     Running     0          47h
prometheus-d8d46c5b5-9ph7s                  1/1     Running     0          47h

我也尝试了kubectl kustomize . | tee xxx.yaml导出yaml文件安装，也失败了

**Comment by Eros11on** [comment]
这个我也吃不大准 根据前面你描述的以及它的报错感觉大概率是网络问题 但也不排除其他问题 
可以先试试我发给你的一些步骤
如果还是这个问题的话 只能一步步查日志排错了

**Comment by DreamerCather** [comment]
好的，谢谢~

**Comment by Eros11on** [comment]
> 好的，谢谢〜

不客气 这个东西挺玄乎的 可以多试试 说不定就成功了 跟版本也有很大的关系

**Comment by qiaoning** [comment]
> 或许你可以留一个邮箱 我可以把自己整理的一个部署文档发给你 参考一下

@Eros11on 
您好，我这边部署，也遇到了同样的问题。failed calling webhook "webhook.cert-manager.io"

辛苦作者发一份部署文档。邮箱地址：420367874@qq.com
