### ISSUE TITLE
方面把镜像放在网盘上吗，搞这些好难！(万分感谢）

### ISSUE THREAD

**Issue by zhangdehai** [Eros11on/Dockerfile-library#2]
谢谢！！

**Comment by Eros11on** [comment]
不好意思 最近比较忙 可以试试$ sudo docker pull registry.cn-beijing.aliyuncs.com/erosion/erosionhub:[镜像版本号]
看看能否直接拉取

**Comment by wallwind** [comment]
构建镜像这块快崩溃了

**Comment by wuchaodzxx** [comment]
执行：
  sudo docker pull registry.cn-beijing.aliyuncs.com/erosion/erosionhub:[镜像名称-版本号]即可，
如：
  docker pull registry.cn-beijing.aliyuncs.com/erosion/erosionhub:viewer-crd-controller-0.2.5
