### ISSUE TITLE
有些吃不准pv.yaml怎么写

### ISSUE THREAD

**Issue by eastlunar** [Eros11on/Dockerfile-library#3]
你好，有些吃不准这些pv.yaml具体怎么写，请问博主可以告诉我metadata-mysql.yaml minmo-pv.yaml mysql-pv.yaml用以参考吗？十分感谢！

**Comment by cherler** [comment]
同问~
按照博主的文章，算是把镜像给pull下来了。但是这个pv 完全陌生不知道怎么弄的

**Comment by cherler** [comment]
搞定了。参考了
https://staight.github.io/2018/08/18/%E8%AE%B0k8s%E7%9A%84%E4%B8%80%E6%AC%A1pv&pvc%E5%88%9B%E5%BB%BA%E8%BF%87%E7%A8%8B/  和  https://www.freesion.com/article/4930622182/#6miniomysql_Podpending_162
