### ISSUE TITLE
有个镜像没在列表中 请问遇到过么

### ISSUE THREAD

**Issue by RichardQin1** [Eros11on/Dockerfile-library#4]
gcr.io/ml-pipeline/ml-pipeline-gcp:bae654dc5cf407359ac5f822d03833768739c4c1
![image](https://user-images.githubusercontent.com/73328199/96960149-3664f200-1534-11eb-8c17-ceb12ea01fbd.png)
请问有遇到过么

**Comment by RichardQin1** [comment]
![image](https://user-images.githubusercontent.com/73328199/96960113-20573180-1534-11eb-9f33-84a09d842703.png)

**Comment by RichardQin1** [comment]
> gcr.io/ml-pipeline/ml-pipeline-gcp:bae654dc5cf407359ac5f822d03833768739c4c1
> ![image](https://user-images.githubusercontent.com/73328199/96960149-3664f200-1534-11eb-8c17-ceb12ea01fbd.png)
> 请问有遇到过么

**Comment by Eros11on** [comment]
你好 这个我也没遇到过 可以试试为这个镜像构造一个dockerfile ，拉取试试
